### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by cindyytong** [sharshi/Web-Hunt#2]
- [x] topics: split this up into a topics table which just lists the topics and another joins table for ProductTopics (many to many relationship) 
- [x] makers table: I don't think you need this for mvps.

**Comment by sharshi** [comment]
How's this:
## `topics`
| column name | data type | details |
|---|---|---|
| `id` | integer | not null, primary key |
| `name` | string | not null, indexed |
| `created_at` | datetime | not null |
| `updated_at` | datetime | not null |

 - `product_id` references `products`

# join-tables

## `products_topics`
| column name | data type | details |
|---|---|---|
| `id` | integer | not null, primary key |
| `product_id` | integer | not null, indexed, foreign key |  
| `topic_id` | integer | not null, indexed, foreign key |  
| `created_at` | datetime | not null |
| `updated_at` | datetime | not null |

 - `product_id` references `products`
 - `topic_id` references `topic`
 - index on `[:topic_id, :product_id], unique: true`
