### ISSUE TITLE
BE and FE Routes 

### ISSUE THREAD

**Issue by cindyytong** [sharshi/Web-Hunt#5]
Hello!

Nice work. Let's meet Monday for kick off meeting.  I'd like to go through the flow of each of your mvps and align on a quick wireframe and strategy for each.  

- [x] If after studying for the assessment this weekend and you have an hour to put together simple wireframes, I highly recommend that for each FE route if you can take a screenshot of the live site and map the user flow to the FE and BE routes it will make the dev of this easier. You're doing some customization to the actual design so it would be good for us to map this out before we build. See example: https://docs.google.com/presentation/d/1XwWw5dBz774zBUmvsu3IOcZAaJGbna1FYvAqtkQ57RQ/edit?usp=sharing
- [x] Add to MVP 2 set up AWS hosting for your images 
- [x]  What kind of products will your site be focused on? We need to think about how we will seed with images. 

FE Routes
- [x] Can we fix formatting to look more similar to the Bluebird clone?
- [x]  Also it's not clear to me what your frontend routes are can you please specify 
- [x] Identify for each FE route if they are auth or protected 
- [x] Rename header to `NavBar` you will need to account for logged in and logged out. For logged in there is also the below
![Screen Shot 2020-02-08 at 4 42 03 PM](https://user-images.githubusercontent.com/13906893/74092444-f89d6780-4a91-11ea-993f-b6c041148c82.png)
- [x]  Links vs left links?  
- [x] `profile` and `profile/edit` allows user to view and edit their profile 
* for goals can we just make this a freeform field for MVP 
- [x] `users/:userId` view users profile:

**Comment by sharshi** [comment]
-  Links vs left links is:
<img width="729" alt="Screen Shot 2020-02-09 at 12 14 41 AM" src="https://user-images.githubusercontent.com/4740525/74096823-ada34480-4ad1-11ea-9abc-b74c944f06ab.png">
 - I think I'll change to NavLinks and SessionLinks
